version: "3"
   
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DB=BookStore
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=hala
      - MYSQL_PASSWORD=hala

  web:
    build: .
    command: sh -c "python3 manage.py migrate &&
                    python3 manage.py runserver" 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
