version: "3"
   
services:
  db:
    image: percona:ps-8
    environment:
      - MYSQL_DB=BookStore
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
